Feature/starksign
starkinfra/core-go pull request #3
Opened 2023-01-31 17:14 UTC by leandro-stark

2023-02-02 16:15 UTC, xavier-stark requested changes

2023-02-02 16:15 UTC, xavier-stark commented on starkcore/utils/request/request.go
> +	Url "github.com/starkinfra/core-go/starkcore/utils/url"
Pq mudou de urls para Url?

2023-02-02 16:15 UTC, xavier-stark commented on tests/sdk/get_test.go
> +//func TestProductLogQuery(t *testing.T) {
opa kkkk

2023-02-02 16:15 UTC, xavier-stark commented on tests/sdk/get_test.go
> +//func TestWorkspaceReplaceQuery(t *testing.T) {
opa kkkk

2023-02-07 20:21 UTC, cdottori-stark approved these changes

2023-02-07 20:22 UTC, xavier-stark approved these changes

2023-02-07 20:22 UTC, merged